# DB auto \uC804\uB7B5
spring.jpa.hibernate.ddl-auto=none

# \uB808\uB514\uC2A4 \uC124\uC815
spring.data.redis.host=redis
spring.data.redis.port=6379

# \uD1A0\uD070 \uC124\uC815
# 6\uC2DC\uAC04
jwt.access-token-validation-period=21600000
# 2\uC77C
jwt.refresh-token-validation-period=172800000