# DB auto \uC804\uB7B5
spring.jpa.hibernate.ddl-auto=update

# \uB808\uB514\uC2A4 \uC124\uC815
spring.data.redis.host=localhost
spring.data.redis.port=6379

# \uB85C\uADF8 \uC124\uC815
logging.level.com.ytk.ytkoj=DEBUG

# \uD1A0\uD070 \uC124\uC815
# 30\uC77C
jwt.access-token-validation-period=2592000000
# 30\uC77C
jwt.refresh-token-validation-period=2592000000